name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  release:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: 'Install Dependencies (Ubuntu)'
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libudev-dev
      - name: 'Build (Release)'
        run: cargo build --release
      - name: 'Upload Artifact (Windows)'
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v7
        with:
          name: rose-offline-client-${{ matrix.os }}
          path: target/release/rose-offline-client.exe
      - name: 'Upload Artifact (Ubuntu, MacOS)'
        if: matrix.os != 'windows-latest'
        uses: actions/upload-artifact@v7
        with:
          name: rose-offline-client-${{ matrix.os }}
          path: target/release/rose-offline-client
